<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\tmgmt\TranslatorInterface;
use Drupal\tmgmt_lokalise\Settings;

/**
 * Implements hook_form_alter().
 */
function tmgmt_lokalise_form_tmgmt_translator_edit_form_alter(&$form, FormStateInterface $form_state) {
  /** @var TranslatorInterface $translator */
  $translator = $form_state->getFormObject()->getEntity();

  if ($translator->getPluginId() !== 'lokalise') {
    return $form;
  }

  $form['plugin_wrapper']['remote_languages_mappings']['#access'] = FALSE;
  return $form;
}

/**
 * Implements hook_entity_presave().
 */
function tmgmt_lokalise_entity_presave(EntityInterface $entity) {
  if ($entity instanceof TranslatorInterface) {
    if ($entity->getPluginId() !== 'lokalise') {
      return;
    }

    $languages = $entity->getSetting(Settings::LANGUAGES);

    // Set back the remote languages mapping.
    $entity->set('remote_languages_mappings', array_map(static function ($data) {
      return $data['remote'];
    }, $languages));

    // Save language settings with remote language.
    $entity->setSetting(Settings::LANGUAGES, array_map(static function ($data) {
      unset($data['remote']);
      return $data;
    }, $languages));
  }
}
